prettify, diff aliases, fixing scripts, quit script

diff --git a/dotfiles/.local/bin/encrypt b/dotfiles/.local/bin/encrypt
--- a/dotfiles/.local/bin/encrypt
+++ b/dotfiles/.local/bin/encrypt
@@ -1,8 +1,8 @@
 #!/bin/bash -e
 
 if [ -z "$1" ]; then
-    echo "Usage: encrypt <filename>"
-    exit 1
+  echo "Usage: encrypt <filename>"
+  exit 1
 fi
 
 base=$(basename "$1")
@@ -10,32 +10,33 @@ dir=$(dirname "$1")
 cd "$dir"
 
 if [ -d "$base" ]; then
-    echo "Zipping $base directory"
-    zip -r "$base.zip" "$base"
-    rm -r "$base"
+  echo "Zipping $base directory"
+  zip -r "$base.zip" "$base"
+  rm -r "$base"
 fi
 
 if [ ! -f "$base" ]; then
-    base="$base.zip"
+  base="$base.zip"
 fi
 
 if [ -f "$base" ]; then
-    read -p -r "Encrypt with (k)ey or (p)assword: " mode
+  read -i "k" -p -r "Encrypt with (K)ey or (p)assword: " mode
+  mode="${mode,,}"
 
-    if [ "$mode" == "k" ]; then
-        echo "Encrypting with key"
-        gpg --encrypt --sign "$base"
-    elif [ "$mode" == "p" ]; then
-        echo "Encrypting with password"
-        gpg --symmetric "$base"
-    else
-        echo "Invalid mode"
-        exit 1
-    fi
-
-    gpgconf --reload gpg-agent
-    rm "$base"
-else
-    echo "No file or directory $base!"
+  if [ "$mode" == "k" ]; then
+    echo "Encrypting with key"
+    gpg --encrypt --sign "$base"
+  elif [ "$mode" == "p" ]; then
+    echo "Encrypting with password"
+    gpg --symmetric "$base"
+  else
+    echo "Invalid mode"
     exit 1
+  fi
+
+  gpgconf --reload gpg-agent
+  rm "$base"
+else
+  echo "No file or directory $base!"
+  exit 1
 fi
